# Site settings
title: give-a-gif
subtitle: by chrgue
email: youremailaddress@gmail.com
description: Isomophic JavaScript with React and spring boot.
baseurl: "/give-a-gif" # the subpath of your site, e.g. /blog
url: "https://chrgue.github.io" # the base hostname & protocol for your site
author: Christian Günther 
city: Berlin
country: Germany

# Link to the actual result
product_url: http://give-a-gif.herokuapp.com/

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 10

# Social settings
github_url: https://github.com/chrgue 
linkedin_url: www.google.de


# Build settings
markdown: kramdown

port: 8081
