# Site settings
title: Give-a-gif
subtitle: by chrgue
email: youremailaddress@gmail.com
description: Isomophic JavaScript with React and spring boot.
baseurl: "/try-nashorn" # the subpath of your site, e.g. /blog
url: "https://chrgue.github.io" # the base hostname & protocol for your site
author: Christian Günther
street_address: 
city: Berlin
state: 
zip_code: 55555
country: Germany
phone:

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown

port: 8081
